server:
  port: 8080

spring:
  application:
    name: webhook-svc

  datasource:
    password: password
    url: jdbc:postgresql://192.168.20.71:5432/poc
    username: pocuser

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: 192.168.20.71:9092
    listener:
      ack-mode: MANUAL

webhook:
  external-url-mapppings: "{'client-1': 'http://localhost:9999/fast', 'client-2': 'http://localhost:9999/slow'}"
  topic: "test-webhook-topic-2"
  executor-thread-pool-size: 10
management:
  endpoints:
    web:
      exposure:
        include: metrics,loggers

logging:
  level:
    root: WARN
    org.vino9.demo: DEBUG

