server:
  port: 8080

spring:
  application:
    name: webhook-svc

  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/poc
    username: pocuser

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: 192.168.20.71:9092
    listener:
      ack-mode: MANUAL

webhook:
  external-url-mapppings: "{'test-webhook-topic-2': 'http://localhost:9999/good', 'test-webhook-topic-3': 'http://localhost:9999/bad'}"
  # topic pattern is a java.util.regex.Pattern
  topic-pattern: "test-webhook-topic-[23]"

management:
  endpoints:
    web:
      exposure:
        include: metrics,loggers

logging:
  level:
    root: WARN
    org.vino9.demo: DEBUG

